accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *


urlpatterns = [
    # User authentication
    url(r'^login/$', LoginUserView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^register/$', RegisterUserView.as_view(), name='register'),

    # User email Verifications
    url(r'^email/verify/$', email_verification, name='email-verification'),
    url(r'^email/send/$', EmailSendFormView.as_view(), name='email_send'),

    # User change password options
    url(
        r'^password/reset/$', PasswordReminderFormView.as_view(),
        name='password-reminder'
    ),
    url(
        r'^password/reset/(?P<reset_code>[a-z0-9\-]+)/$',
        PasswordResetFormView.as_view(), name='password-reset'
    ),

    url(r'^change-password/$', change_password, name='change-password'),

    # User profile options
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/complete/$', profile_complete, name='profile-complete'),
    url(r'^profile/extra/$', profile_extra, name='profile-extra'),

    url(r'^get-localidades/$', get_localidades, name='get-localidades'),
    url(r'^data/$', data, name='data'),

    # User delete options
    url(r'^delete/$', delete_account, name='delete-account'),
    url(r'^confirm/(?P<token>[a-z0-9\-]+)/$', confirm_deletion, name='registration-confirm-deletion')
]

baid/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from baid import views

handler404 = 'baid.views.handler404'
handler500 = 'baid.views.handler500'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    url('', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
import logging
import simplejson
import calendar
from datetime import *

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q


NACIONALIDAD_POR_DEFECTO = 'AR'
PROVINCIA_POR_DEFECTO = 3
TD_DEFECTO = 1
GENERO_POR_DEFECTO = 1

logger = logging.getLogger(__name__)


class EmailVerification(models.Model):
    # TODO Queda pendiente verificacion de Juani. Si esto se hace complejo,
    # volverlo a poner como ForeignKey
    user = models.OneToOneField(User)
    code = models.CharField(max_length=60)
    date_sent = models.DateTimeField(auto_now_add=True)


class PasswordResetCode(models.Model):
    user = models.OneToOneField(User)
    code = models.CharField(max_length=60)
    consumed = models.BooleanField(default=False)
    date_sent = models.DateTimeField()


class TipoDocumento(models.Model):
    class Meta:
        ordering = ["tipo", ]

    tipo = models.CharField(null=False, max_length=30, blank=False, unique=True)

    def __repr__(self):
        return "<Tipo Documento:{tipo}>".format(tipo=self.tipo)


class Nacionalidad(models.Model):
    class Meta:
        ordering = ["nombre", ]
    nombre = models.CharField(null=False, blank=True, max_length=50,
                              unique=True)
    codigo = models.CharField(null=False, blank=True, max_length=3,
                              unique=True)


class Provincia(models.Model):
    nombre = models.CharField(null=False, blank=False, max_length=100,
                              unique=True)


class Localidad(models.Model):
    nombre = models.CharField(null=False, blank=False, max_length=100)
    provincia = models.ForeignKey(Provincia)


class Genero(models.Model):
    nombre = models.CharField(null=False, blank=False, max_length=20)


class ExtendedProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    tipo_documento = models.ForeignKey(TipoDocumento, null=True, blank=True)
    numero_documento = models.CharField(max_length=100, null=True, blank=True)
    nacionalidad = models.ForeignKey(Nacionalidad, null=True, blank=True)
    altura = models.IntegerField(null=True)
    piso = models.CharField(null=True, blank=True, max_length=50)
    departamento = models.CharField(null=True, blank=True, max_length=50)
    localidad = models.ForeignKey(Localidad, null=True)
    comuna = models.CharField(null=True, blank=True, max_length=100)
    email_alternativo = models.CharField(null=True, blank=True, max_length=100)
    cuit_cuil = models.CharField(null=True, blank=True, max_length=100)
    provincia = models.ForeignKey(Provincia, null=True, blank=True)

    nombre = models.CharField(max_length=255, blank=True, null=True)
    apellido = models.CharField(max_length=255, blank=True, null=True)
    genero = models.CharField(max_length=100, choices=[('M', 'Male'), ('F', 'Female')], null=True)
    fecha_nacimiento = models.DateField(null=True)
    numero_telefono = models.CharField(max_length=255, blank=True, null=True)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    codigo_postal = models.CharField(max_length=255, blank=True, null=True)
    fecha_modificacion = models.DateTimeField(auto_now_add=True)
    avatar = models.CharField(max_length=255, blank=True, null=True)

    @classmethod
    def profile(cls, username):
        try:
            p = ExtendedProfile.objects.filter(user__username=username).first()
        except Exception as e:
            logger.error(e)
            p = None
        return p


class DeletedUser(models.Model):
    user_information = models.TextField()
    deleted_date = models.DateField(auto_now=True)
    identifier = models.TextField(null=False, blank=False, db_index=True)


class UserInfo(object):

    @classmethod
    def get_by_user(cls, user):
        """
        This classmethod belongs to `django-oidc-provider`.
        See: https://github.com/juanifioren/django-oidc-provider/blob/v0.2.x/DOC.md#standard-claims
        """
        ep = ExtendedProfile.objects.get(user=user)
        class bare(object): pass

        bare.given_name = ep.nombre
        bare.family_name = ep.apellido
        bare.picture = ep.avatar
        bare.gender = ep.genero
        bare.birthdate = ep.fecha_nacimiento.isoformat() if ep.fecha_nacimiento else ''
        bare.updated_at = ep.fecha_modificacion.isoformat() if ep.fecha_modificacion else ''
        bare.email = user.email
        bare.email_verified = user.is_active
        bare.address_street_address = ep.direccion
        bare.address_locality = ep.localidad.nombre if ep.localidad else ''
        bare.address_region = ep.provincia.nombre if ep.provincia else ''
        bare.address_country = ep.nacionalidad.nombre if ep.nacionalidad else ''
        bare.address_postal_code = ep.codigo_postal
        bare.phone_number = ep.numero_telefono

        return bare

accounts/views.py
# -*- coding: utf-8 -*-
import json
import logging

from datetime import date
from uuid import uuid4
from urllib import quote
from urlparse import urlparse

from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.cache import cache
from django.template import RequestContext
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, resolve_url, render_to_response
from django.template.loader import render_to_string, select_template
from django.views.generic import FormView
from django.utils.http import is_safe_url
from django.utils.translation import gettext as _
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.forms.utils import ErrorList
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect

from accounts.decorators import *
from accounts.forms import *
from accounts.models import *
from accounts.utils import *

from social.backends.open_id import OpenIdConnectAuth
from social.exceptions import AuthMissingParameter

logger = logging.getLogger(__name__)


def login(request):
    """
    Displays the login form and handles the login action.
    It's a rewrite of django login view, this requires the end user to
    authenticate using email instead of username.
    """

    redirect_to = request.POST.get(REDIRECT_FIELD_NAME,
                                   request.GET.get(REDIRECT_FIELD_NAME, ''))

    if redirect_to:
        redirect_path = '?{0}={1}'.format(REDIRECT_FIELD_NAME,
                                          quote(redirect_to))

    if request.user.is_authenticated():
        return redirect(redirect_to or reverse('accounts:profile'))

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        if email and password:
            email = email.lower()
            try:
                # TODO Should use something different, we can't actually
                # insert the records, because in current baid we have
                # users with email greater than 30 chars
                user = User.objects.get(email=email)
                auth_user = authenticate(username=user.username,
                                         password=password)
                if auth_user:
                    if not user.is_active:
                        activate_url = create_email_verification_url(request, user)
                        if redirect_to:
                            activate_url += redirect_path
                        send_email_verification(email, activate_url)
                        return render(request, 'accounts/email_sent.html', {
                            'email': user.email,
                        })
                    # Log the user in.
                    auth_login(request, auth_user)
                    return redirect(redirect_to or reverse('accounts:profile'))
                else:
                    msg = _(u'El correo electrónico y contraseña son invalidos.')
                    messages.add_message(request, messages.ERROR, msg)
            except User.DoesNotExist:
                msg = _(u'El usuario no existe')
                messages.add_message(request, messages.ERROR, msg)
        else:
            msg = _(u'Falta correo electrónico o contraseña')
            messages.add_message(request, messages.ERROR, msg)

    # Create the url for registration and password recovery.
    register_url = reverse('accounts:register')
    reset_url = reverse('accounts:password-reminder')
    if redirect_to:
        redirect_path = '?{0}={1}'.format(REDIRECT_FIELD_NAME,
                                          quote(redirect_to))
        register_url += redirect_path
        reset_url += redirect_path

    context = {
        REDIRECT_FIELD_NAME: redirect_to,
        'register_url': register_url,
        'reset_url': reset_url,
    }

    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)

    redirect_to = request.POST.get(REDIRECT_FIELD_NAME,
                                   request.GET.get(REDIRECT_FIELD_NAME, ''))

    return HttpResponseRedirect(redirect_to or reverse('accounts:login'))


class RedirectFormMixin(FormView):
    """
    Redirect to Form Mixin
    Mixin View agrega funcionalidad de redirect("next") a los Formviews que requieran.
    * Heredar primero
    """

    @property  # workaround
    def redirect_to(self):
        """
        Indica la URL a la que necesita redireccionarse en caso de venir desde un cliente o cualquier pagina
        :return:
        """
        # todo DRY, intecionalmente repetido para no quebrar, se armo un quilombete con un revert donde se quito codigo
        redirect_to = self.request.POST.get(REDIRECT_FIELD_NAME, self.request.GET.get(REDIRECT_FIELD_NAME, ''))

        return redirect_to

    @property
    def redirect_path(self):
        """
        Redirect path
        :return:
        """
        if self.redirect_to:
            return '?{0}={1}'.format(REDIRECT_FIELD_NAME, quote(self.redirect_to))
        return ''

    def get_redirect_to_value(self):
        """
        Obtiene/retorna valor de "Next" en caso de existir/recibirlo via GET o POST
        """
        return self.request.POST.get(
            REDIRECT_FIELD_NAME,
            self.request.GET.get(REDIRECT_FIELD_NAME, '')
        )

    def get_redirect_url(self, multiple_params=False):
        """
        Retorna URL lista para concatenar
        Ejemplo: &next=REDIRECT_VALUE
        """
        if self.get_redirect_to_value():
            url = '{0}next={1}'.format(
                '&' if multiple_params else '?',
                quote(self.get_redirect_to_value()))
        else:
            url = ''

        return url

    def get_initial(self):
        """
        Valor Inicial para todos los Formview Childs interesados.
        """
        redirect_to = self.get_redirect_to_value()
        return {'next': redirect_to}


class LoginUserView(RedirectFormMixin):
    """
    Login User View
    @watch_logins
    """
    form_class = LoginUserForm
    template_name = 'accounts/login.html'

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():  # workaround se fue todo a la nada con un revert..
            return redirect(self.redirect_to or reverse('accounts:profile'))

        return super(LoginUserView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(LoginUserView, self).get_context_data(**kwargs)

        redirect_url = self.get_redirect_url()

        context['next'] = self.get_redirect_to_value()

        context['register_url'] = reverse('accounts:register')
        context['register_url'] += redirect_url

        context['reset_url'] = reverse('accounts:password-reminder')
        context['reset_url'] += redirect_url

        return context

    def form_valid(self, form):
        email = form.cleaned_data['email'].lower()
        password = form.cleaned_data['password']

        user = User.objects.get(email=email)
        auth_user = authenticate(username=user.username, password=password)

        if auth_user:
            if not user.is_active:
                activate_url = create_email_verification_url(self.request, user)
                if self.redirect_to:
                    activate_url += self.redirect_path
                    send_email_verification(email, activate_url)
                    return render(self.request, 'accounts/email_sent.html', {'email': user.email})

            auth_login(self.request, auth_user)
            return redirect(self.redirect_to or reverse('accounts:profile'))

        else:
            form._errors['email'] = ErrorList([_(u'El correo electrónico y contraseña son invalidos.')])
            return self.form_invalid(form)

        return redirect(reverse('accounts:profile'))


class RegisterUserView(RedirectFormMixin):
    """
    Register user view
    """
    form_class = RegisterUserForm
    template_name = 'accounts/register.html'
    template_success_name = 'accounts/email_sent.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.get_redirect_to_value() or 'accounts:profile')

        return super(RegisterUserView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(RegisterUserView, self).get_context_data(**kwargs)

        context['next'] = self.get_redirect_to_value()

        return context

    def form_valid(self, form):
        email = form.cleaned_data['email'].lower()
        password = form.cleaned_data['password']

        if User.objects.filter(email=email).count():
            form._errors['email'] = ErrorList([_(u'El correo electrónico ya ha sido registrado. Intenta ingresar.')])
            return self.form_invalid(form)

        username = generate_unique_username(email)
        user = User.objects.create_user(username, email, password)
        user.is_active = False
        user.save()

        activate_url = create_email_verification_url(self.request, user)
        activate_url += self.get_redirect_url(multiple_params=True)

        send_email_verification(email, activate_url)

        return render_to_response(

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
        <h1 class="h3 text-center">{% trans 'Cambiá tu contraseña' %}</h1>
        <br>
	<form action="{% url 'accounts:change-password' %}" method="POST">
          <div class="form-group">
            <label class="control-label" for="old_password">{% trans 'Contraseña actual' %}</label>
	    {{form.old_password}}

	    {%if form.old_password.errors%}
		<div class="alert alert-danger">{{form.old_password.errors}}</div>
	    {%endif%}

          </div>

          <div class="form-group">
            <label class="control-label" for="new_password1">{% trans 'Nueva contraseña' %}</label>
	    {{form.new_password1}}
	    {%if form.new_password1.errors%}
	    	<div class="alert alert-danger">{{form.new_password1.errors}}</div>
	    {%endif%}
          </div>

          <div class="form-group">
            <label class="control-label" for="new_password2">{% trans 'Confirmar nueva contraseña' %}</label>
	    {%if form.new_password2.errors %}
		<div class="alert alert-danger">{{form.new_password2.errors}}</div>
	    {%endif%}
	    {{form.new_password2}}
          </div>
          <br>
          <button class="btn btn-primary btn-xl btn-block">{% trans 'Aceptar' %}</button>
	  {% csrf_token %}
        </form>
        <br>
        <p class="text-center">
          <a href="{% url 'accounts:data' %}" class="btn btn-link btn-block">{% trans 'Volver' %}</a>
          <a href="#" class="btn btn-link btn-block" target="_blank">{% trans 'Términos de uso y privacidad' %}</a>
        </p>
{% endblock %}

accounts/templates/accounts/data.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
        <!-- div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          Datos cambiados con éxito.
        </div -->
        <h1 class="h3 text-center">{% trans 'Datos de Cuenta' %}</h1>
        <br>
        <form>

          <div class="form-group">
            <label class="control-label" for="email">{% trans 'Correo electrónico' %}</label>
            <input class="form-control" type="text" placeholder="{% trans 'Correo electrónico' %}" name="email" value="{{ email }}" disabled="true">
          </div>

          <div class="form-group">
            <label class="control-label" for="">{% trans 'Contraseña' %}</label><br>
	    <a href="{% url 'accounts:change-password' %}" class="btn btn-default btn-block">{% trans 'Cambiar contraseña' %}</a>
          </div>
        </form>
        <br>
        <p class="text-center">
          <a href="{% url 'accounts:delete-account' %}" class="btn btn-link btn-block">{% trans 'Borrar cuenta' %}</a>
          <a href="#" class="btn btn-link btn-block" target="_blank">{% trans 'Términos de uso y privacidad' %}</a>
        </p>
{% endblock %}

accounts/templates/accounts/delete_account.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
        <div class="text-center">
          <div class="icon icon-danger"></div>
          <h1 class="h2">{% trans '¿Estás seguro que querés borrar tu cuenta?' %}</h1>
          <p>{% trans 'Borrando tu cuenta vas a perder la posibilidad de hacer tus trámites de manera online y acceder a todos los beneficios y notificaciones de servicios.' %}</p>
          <br><br>

            <form action="{% url 'accounts:delete-account' %}" method="POST">
  	  <button class="btn btn-danger btn-xl btn-block" value="1" name="borrar"/>{% trans 'Borrar cuenta' %}</button>

	  {% csrf_token %}
  	  </form>
          <br>
          <br>
          <a href="{% url 'accounts:data' %}" class="btn btn-link btn-block">{% trans 'Volver' %}</a>
          <a href="#" class="btn btn-link btn-block" target="_blank">{% trans 'Términos de uso y privacidad' %}</a>
        </div>
{% endblock %}

accounts/templates/accounts/email_message.html
{% load i18n %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Open BA ID</title>
  </head>
  <body style="margin: 0;">

    <!-- Contenido del email -->
    <div style="padding: 10px; text-align: center; background-image: -webkit-gradient(linear, left top, left bottom, from(#ffd300), to(#ffbc00)); background-image: -webkit-linear-gradient(top, #ffd300 0%, #ffbc00 100%); background-image: linear-gradient(to bottom, #ffd300 0%, #ffbc00 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffd300', endColorstr='#ffbc00',GradientType=0 ); background-color: #ffbc00; border-color: #d7a721; color: #5f4600;">
      <img src="{{ request.build_absolute_uri }}static/img/openbaid-logo.png" alt="Open BA ID">
    </div>

    <div style="font-family: 'OpenSans', Helvetica, Arial, sans-serif;">
      <div style="max-width: 630px; padding-right: 15px; padding-left: 15px; margin-right: auto; margin-left: auto;">
        <h3 style="margin: 40px 0 30px; color: #333; font-size: 20px; line-height: 1.1; font-family: 'Gotham', Helvetica, Arial, sans-serif;">{% trans '¡Gracias por registrar tu cuenta!' %}</h3>
        <p>{% trans 'Necesitamos confirmar tu dirección de correo electrónico para que puedas empezar a usar todos los servicios que te permite acceder tu cuenta.' %}</p>
        <br>
        <br>
        <p style="text-align: center; font-size: .9em;">
          <a href="{{ activate_url }}" style="display: inline-block; padding: 15px 25px; font-size: 18px; text-decoration: none; font-weight: bold; line-height: 1.33; border: 1px solid transparent; border-radius: 6px;background-image: -webkit-gradient(linear, left top, left bottom, from(#ffd300), to(#ffbc00)); background-image: -webkit-linear-gradient(top, #ffd300 0%, #ffbc00 100%); background-image: linear-gradient(to bottom, #ffd300 0%, #ffbc00 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffd300', endColorstr='#ffbc00',GradientType=0 ); background-color: #ffbc00; border-color: #d7a721; color: #5f4600;">{% trans 'Activar mi cuenta' %}</a>
        </p>
        <br>
        <br>
        <p style="word-break: break-word; font-size: .9em;">{% trans 'Por favor entrá con el botón de arriba o ingresá a' %}
          <a href="{{ activate_url }}">{{ activate_url }}</a>
        </p>
      </div>
    </div>
    <!-- Fin Contenido del email -->

  </body>
</html>

accounts/templates/accounts/email_send.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

    <h1>{% trans 'Activar mi cuenta' %}</h1>
    <p>{% trans 'Te enviaremos un email a:' %}</p>

    {% if form.errors.email %}
        <div class="alert alert-danger">{{ form.errors.email }}</div>
    {% endif %}

    <form method="post" action="{% url 'accounts:email_send' %}">
        {% csrf_token %}
        <div class="form-group {% if form.errors.email %}has-error{% endif %}">
            {{ form.email }}
        </div>
        <div class="g-recaptcha">
            {{ form.captcha }}
        </div>
        {{ form.next }}
        <br>
        <button class="btn btn-primary btn-xl btn-block">{% trans 'Enviar' %}</button>
    </form>
    
{% endblock %}

accounts/templates/accounts/email_verification.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div class="text-center">
    {% if error %}
        <h1>Ups!</h1>
        <p>{% trans 'Ocurrio un error. Intenta activar tu cuenta nuevamente.' %}</p>
        <a href="{% url 'accounts:email_send' %}" class="btn btn-default">{% trans 'Activar Cuenta' %}</a>
    {% else %}
        <h1>{% trans 'Tu cuenta fue verificada!' %}</h1>
        <a href="{{ login_url }}" class="btn btn-lg btn-default btn-block">{% trans 'Continuar' %}</a>
    {% endif %}
</div>

{% endblock %}

accounts/templates/accounts/profile_complete.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block stylesheets %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.css' %}">

{% endblock %}

{% block content %}
    {% if not has_profile %}
    <h1 class="h3 text-center">{% trans 'Por favor completá estos datos para finalizar el registro' %}</h1>
    {% else %}
    <h1 class="h3 text-center">{% trans 'Datos personales' %}</h1>
    {% endif %}
    <br>
    <form method="POST" action="{% url 'accounts:profile-complete' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group {% if error.first_name %}has-error{% endif %}">
            <label class="control-label" for="nombres">{% trans 'Nombres' %}</label>
            <input class="form-control" type="text" placeholder="Ej: Juan Alberto" name="first_name" value="{{ data.first_name }}">
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group {% if error.last_name %}has-error{% endif %}">
            <label class="control-label" for="apellidos">{% trans 'Apellidos' %}</label>
            <input class="form-control" type="text" placeholder="Ej: Perez" name="last_name" value="{{ data.last_name }}">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-6">
          <div class="form-group {% if error.tipo_documento %}has-error{% endif %}">
            <label class="control-label">{% trans 'Documento' %}</label>
            <select class="form-control" name="tipo_documento">
              <option value="{{ data.tipo_documento }}" selected>{{ data.tipo_documento | upper }}</option>
              {% for tipo in tipos_documentos %}
              <option value="{{ tipo }}">{{ tipo | upper }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="form-group {% if error.numero_documento %}has-error{% endif %}">
            <label class="control-label">{% trans 'Número' %}</label>
            <input class="form-control" type="text" placeholder="Ej: 31765123" name="numero_documento" value="{{ data.numero_documento }}">
          </div>
        </div>
      </div>

      <div class="form-group {% if error.gender %}has-error{% endif %}">
        <label class="control-label">{% trans 'Genero' %}</label>
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <label href="#" class="btn btn-default {% ifequal data.gender 'F' %}active{% endifequal %}">
            <input type="radio" name="gender" value="F" class="hidden" {% ifequal data.gender 'F' %}active{% endifequal %}> {% trans 'Femenino' %}
          </label>
          <label href="#" class="btn btn-default {% ifequal data.gender 'M' %}active{% endifequal %}">
            <input type="radio" name="gender" value="M" class="hidden" {% ifequal data.gender 'M' %}checked{% endifequal %}> {% trans 'Masculino' %}
          </label>
        </div>
      </div>

      <div class="form-group form-date {% if error.birthdate %}has-error{% endif %}" style="position:relative">
        <label class="control-label" for="birthdate">{% trans 'Fecha de nacimiento' %}</label>
        <input class="form-control" type="text" placeholder="{% trans 'Ej: 07/07/1985' %}" id="birthdate" name="birthdate" value="{{ data.birthdate }}">
      </div>

      <br>
      <input type="submit" class="btn btn-primary btn-xl btn-block" value="{% trans 'Continuar' %}">
      <br>
      <a href="#" class="btn btn-link btn-block" target="_blank">{% trans 'Términos de uso y privacidad' %}</a>
    </form>
{% endblock %}

{% block scripts %}

  <script src="{% static 'js/moment.js' %}"></script>
  <script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
  <script type="text/javascript">
    $(function () {
      $('#birthdate').datetimepicker({
        locale: 'es',
        format: 'DD/MM/YYYY'
      });
      if ("{{ data.tipo_documento }}" === "") {
        $( "select[name=tipo_documento] option[value=dni]" ).prop('selected', true);
      };
    });
  </script>

{% endblock %}