accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *


urlpatterns = [
    # User authentication
    url(r'^login/$', LoginUserView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^register/$', RegisterUserView.as_view(), name='register'),

    # User email Verifications
    url(r'^email/verify/$', email_verification, name='email-verification'),
    url(r'^email/send/$', EmailSendFormView.as_view(), name='email_send'),

    # User change password options
    url(
        r'^password/reset/$', PasswordReminderFormView.as_view(),
        name='password-reminder'
    ),
    url(
        r'^password/reset/(?P<reset_code>[a-z0-9\-]+)/$',
        PasswordResetFormView.as_view(), name='password-reset'
    ),

    url(r'^change-password/$', change_password, name='change-password'),

    # User profile options
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/complete/$', profile_complete, name='profile-complete'),
    url(r'^profile/extra/$', profile_extra, name='profile-extra'),

    url(r'^get-localidades/$', get_localidades, name='get-localidades'),
    url(r'^data/$', data, name='data'),

    # User delete options
    url(r'^delete/$', delete_account, name='delete-account'),
    url(r'^confirm/(?P<token>[a-z0-9\-]+)/$', confirm_deletion, name='registration-confirm-deletion')
]

baid/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from baid import views

handler404 = 'baid.views.handler404'
handler500 = 'baid.views.handler500'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    url('', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

baid/views.py
# -*- coding: utf-8 -*-
import time
from django.shortcuts import redirect, HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

def home(request):
    return redirect('accounts:login')


def handler404(request):
    response = render(request, '404.html')
    response.status_code = 404
    return response


def handler500(request):
    response = render(request, '500.html')
    response.status_code = 500
    return response

baid/templates/base.html
{% extends "base_without_nav.html" %}

{% load i18n %}
{% load staticfiles %}

{% block navigation %}

    {% if user.is_authenticated and not hide_nav %}
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="dropdown user-name hidden-xs">
            <a href="#user-menu" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user.email }} <span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-menu-left" role="menu">
              <li class="dropdown-header">{% trans 'Mis datos' %}</li>
              <li><a href="{% url 'accounts:profile-complete' %}">{% trans 'Personales' %}</a></li>
              <li><a href="{% url 'accounts:profile-extra' %}">{% trans 'Opcionales' %}</a></li>
              <li><a href="{% url 'accounts:data' %}">{% trans 'Cuenta' %}</a></li>
              {% if user.is_superuser %}
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'admin:index' %}" target="_blank">{% trans 'Admin' %}</a></li>
              {% endif %}
            </ul>
          </li>
          <li class="visible-xs"><a href="#mobileMenu" data-toggle="collapse" aria-expanded="false" aria-controls="mobileMenu">{{ user.email }} <span class="caret"></span></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'accounts:logout' %}">{% trans 'Salir' %}</a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="visible-xs">
          <div class="collapse" id="mobileMenu">
            <ul class="nav navbar-nav" role="menu">
            <li><a href="{% url 'accounts:profile-extra' %}">{% trans 'Datos para trámites' %}</a></li>
              <li><a href="{% url 'accounts:profile-complete' %}">{% trans 'Datos personales' %}</a></li>
              <li><a href="{% url 'accounts:data' %}">{% trans 'Datos de cuenta' %}</a></li>
              {% if user.is_superuser %}
              <li><a href="{% url 'admin:index' %}" target="_blank">{% trans 'Admin' %}</a></li>
              {% endif %}
            </ul>
        </div>
      </div>
    </nav>
    {% endif %}

{% endblock %}

baid/templates/base_without_nav.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7]><html lang="es" class="lt-ie10 lt-ie9 lt-ie8 lt-ie7 "><![endif]-->
<!--[if IE 7]><html lang="es" class="lt-ie10 lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html lang="es" class="lt-ie10 lt-ie9 "> <![endif]-->
<!--[if IE 9]><html lang="es" class="lt-ie10 "> <![endif]-->
<!--[if gt IE 9]><!--> <html lang="es" class=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sitio externo del Gobierno de la Ciudad de Buenos Aires.">
    <meta name="author" content="Gobierno de la Ciudad de Buenos Aires">
    <title>Open BA ID</title>
    <!--link rel="shortcut icon" href="{% static 'bootstrap3/favicon.ico' %}"-->
    <!--link rel="apple-touch-icon-precomposed" href="{% static 'bootstrap3/favicon-mobile.png' %}"-->
    <link rel="stylesheet" href="{% static 'bootstrap3/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/baid-styles.css' %}">

    <!-- ESTILOS EXTRA -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block stylesheets %}{% endblock %}
</head>
<body>

    <header class="navbar navbar-inverse navbar-top">
        <div class="container">
            <a class="navbar-brand bac-header text-center" href="{% url 'home' %}">Open BA ID</a>
        </div>
    </header>

    {% block navigation %}{% endblock %}

    {% block afternav %}{% endblock %}

    <!-- CONTENIDO -->
    <main class="main-container" role="main">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>
    <!-- FIN DE CONTENIDO -->

    <script src="{% static 'bootstrap3/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap3/bootstrap.min.js' %}"></script>

    {% block scripts %}{% endblock %}

</body>
</html>